# Generated by Django 5.1.4 on 2025-03-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emploi_Temps', '0002_calendrier_filiere_disponibilite_exception_groupe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='credits',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='filiere',
            field=models.CharField(choices=[('TC', 'Tronc Commun'), ('DWM', 'Développement Web et Mobile'), ('DSI', 'Développement des Systèmes Informatiques'), ('RSS', 'Réseaux et Sécurité des Systèmes')], max_length=10),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='semestre',
            field=models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2'), (3, 'Semestre 3'), (4, 'Semestre 4'), (5, 'Semestre 5'), (6, 'Semestre 6')]),
        ),
    ]
