# Generated by Django 5.1.4 on 2025-03-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emploi_Temps', '0003_alter_matiere_code_alter_matiere_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='filiere',
            field=models.CharField(choices=[('TC', 'Tronc Commun'), ('DWM', 'Développement Web et Mobile'), ('DSI', 'Développement de Systèmes Informatiques'), ('RSS', 'Réseaux et Sécurité des Systèmes')], max_length=10),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
