# Generated by Django 5.1.4 on 2025-03-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emploi_Temps', '0004_alter_matiere_filiere_alter_matiere_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='credits',
            field=models.IntegerField(),
        ),
    ]
