# Generated by Django 5.1.4 on 2025-03-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emploi_Temps', '0003_chargehebdo_disponibilites_enseignant_and_more'),
        ('Emploi_Temps', '0005_alter_matiere_credits'),
    ]

    operations = [
    ]
