# Generated by Django 5.1.4 on 2025-03-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emploi_Temps', '0006_merge_20250309_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploitemps',
            name='creneau_fixe',
            field=models.BooleanField(default=False),
        ),
    ]
